/-
  Linen.Database.PostgreSQL.LibPQ — Low-level libpq FFI bindings

  Direct Lean 4 bindings to PostgreSQL's libpq C library.  Each function
  corresponds to a libpq API call, wrapped with Lean's `IO` monad for
  safety and with opaque external objects (`PgConn`/`PgResult`) for
  automatic resource management via GC finalizers (`PQfinish`/`PQclear`).

  The pure status enums and helper structures live in
  `Linen.Database.PostgreSQL.LibPQ.Types`.

  ## Haskell source
  - `Database.PostgreSQL.LibPQ` (postgresql-libpq package)

  ## FFI
  - Implementation in `ffi/postgres.c` (symbols `linen_pg_*`).
  - Requires libpq headers/lib, resolved via `pkg-config libpq` in the
    lakefile; libpq is therefore a build-time dependency of the library.

  Because these are live database operations, they cannot be exercised by
  `#guard`/`#eval`; the test suite only typechecks the signatures.
-/

import Linen.Database.PostgreSQL.LibPQ.Types

namespace Database.PostgreSQL.LibPQ

-- ────────────────────────────────────────────────────────────────────
-- Connection management
-- ────────────────────────────────────────────────────────────────────

/-- Connect to a PostgreSQL database using a connection string.
    $$\text{connect} : \text{String} \to \text{IO}\ \text{PgConn}$$
    The connection string follows libpq format:
    `"host=localhost port=5432 dbname=mydb user=myuser"` or a URI
    `"postgresql://user:pass@host/db"`. -/
@[extern "linen_pg_connect"]
opaque connect (conninfo : @& String) : IO PgConn

@[extern "linen_pg_status"]
private opaque statusRaw (conn : @& PgConn) : IO UInt8

/-- Return the status of the connection.
    $$\text{status} : \text{PgConn} \to \text{IO}\ \text{ConnStatus}$$ -/
def status (conn : @& PgConn) : IO ConnStatus := do
  let raw ← statusRaw conn
  return ConnStatus.ofUInt8 raw

/-- Return the error message most recently generated by a connection operation. -/
@[extern "linen_pg_error_message"]
opaque errorMessage (conn : @& PgConn) : IO String

/-- Close the connection immediately (before GC would finalize it). -/
@[extern "linen_pg_close"]
opaque close (conn : @& PgConn) : IO Unit

-- ────────────────────────────────────────────────────────────────────
-- Query execution
-- ────────────────────────────────────────────────────────────────────

/-- Execute a simple SQL command (no parameters).
    $$\text{exec} : \text{PgConn} \to \text{String} \to \text{IO}\ \text{PgResult}$$ -/
@[extern "linen_pg_exec"]
opaque exec (conn : @& PgConn) (query : @& String) : IO PgResult

/-- Execute a parameterized query.
    Parameters are passed as an array of optional strings (`none` = SQL NULL).
    $$\text{execParams} : \text{PgConn} \to \text{String} \to
      \text{Array}\ (\text{Option String}) \to \text{IO}\ \text{PgResult}$$ -/
@[extern "linen_pg_exec_params"]
opaque execParams (conn : @& PgConn) (query : @& String)
    (params : @& Array (Option String)) : IO PgResult

/-- Prepare a named statement for later execution.
    $$\text{prepare} : \text{PgConn} \to \text{String} \to \text{String} \to
      \text{IO}\ \text{PgResult}$$ -/
@[extern "linen_pg_prepare"]
opaque prepare (conn : @& PgConn) (stmtName : @& String)
    (query : @& String) : IO PgResult

/-- Execute a previously prepared statement with the given parameters. -/
@[extern "linen_pg_exec_prepared"]
opaque execPrepared (conn : @& PgConn) (stmtName : @& String)
    (params : @& Array (Option String)) : IO PgResult

-- ────────────────────────────────────────────────────────────────────
-- Result inspection
-- ────────────────────────────────────────────────────────────────────

@[extern "linen_pg_result_status"]
private opaque resultStatusRaw (result : @& PgResult) : IO UInt8

/-- Return the result status of a query. -/
def resultStatus (result : @& PgResult) : IO ExecStatus := do
  let raw ← resultStatusRaw result
  return ExecStatus.ofUInt8 raw

/-- Return the error message associated with a result, or empty string. -/
@[extern "linen_pg_result_error_message"]
opaque resultErrorMessage (result : @& PgResult) : IO String

/-- Return the number of rows in the result set. -/
@[extern "linen_pg_ntuples"]
opaque ntuples (result : @& PgResult) : IO UInt32

/-- Return the number of columns in the result set. -/
@[extern "linen_pg_nfields"]
opaque nfields (result : @& PgResult) : IO UInt32

/-- Return the value at the given row and column as a string. -/
@[extern "linen_pg_getvalue"]
opaque getvalue (result : @& PgResult) (row : UInt32) (col : UInt32) : IO String

/-- Return whether the value at the given position is NULL. -/
@[extern "linen_pg_getisnull"]
opaque getIsNull (result : @& PgResult) (row : UInt32) (col : UInt32) : IO Bool

/-- Return the column name at the given index. -/
@[extern "linen_pg_fname"]
opaque fname (result : @& PgResult) (col : UInt32) : IO String

/-- Return the OID of the column type at the given index. -/
@[extern "linen_pg_ftype"]
opaque ftype (result : @& PgResult) (col : UInt32) : IO UInt32

/-- Return the number of rows affected by the command (as a string). -/
@[extern "linen_pg_cmd_tuples"]
opaque cmdTuples (result : @& PgResult) : IO String

-- ────────────────────────────────────────────────────────────────────
-- Escaping
-- ────────────────────────────────────────────────────────────────────

/-- Escape a string for use as an SQL literal (adds quotes).
    $$\text{escapeLiteral} : \text{PgConn} \to \text{String} \to \text{IO}\ \text{String}$$ -/
@[extern "linen_pg_escape_literal"]
opaque escapeLiteral (conn : @& PgConn) (str : @& String) : IO String

/-- Escape a string for use as an SQL identifier (adds double-quotes). -/
@[extern "linen_pg_escape_identifier"]
opaque escapeIdentifier (conn : @& PgConn) (str : @& String) : IO String

-- ────────────────────────────────────────────────────────────────────
-- LISTEN / NOTIFY
-- ────────────────────────────────────────────────────────────────────

/-- Consume any available input from the server (non-blocking).
    Returns `true` if no error occurred. -/
@[extern "linen_pg_consume_input"]
opaque consumeInput (conn : @& PgConn) : IO Bool

/-- Return the next notification from the server, if any. -/
@[extern "linen_pg_notifies"]
opaque notifies (conn : @& PgConn) : IO (Option PgNotification)

-- ────────────────────────────────────────────────────────────────────
-- Transaction state
-- ────────────────────────────────────────────────────────────────────

@[extern "linen_pg_transaction_status"]
private opaque transactionStatusRaw (conn : @& PgConn) : IO UInt8

/-- Return the current in-transaction status of the server. -/
def transactionStatus (conn : @& PgConn) : IO TransactionStatus := do
  let raw ← transactionStatusRaw conn
  return TransactionStatus.ofUInt8 raw

-- ────────────────────────────────────────────────────────────────────
-- Convenience: check result or throw
-- ────────────────────────────────────────────────────────────────────

/-- Execute a query and check the result status.  Throws `IO.userError`
    if the result indicates an error. -/
def execCheck (conn : PgConn) (query : String) : IO PgResult := do
  let res ← exec conn query
  let st ← resultStatus res
  if st.isOk then
    return res
  else
    let msg ← resultErrorMessage res
    throw (IO.userError s!"PostgreSQL error: {msg}")

/-- Connect and verify the connection is OK.  Throws `IO.userError`
    if the connection failed. -/
def connectCheck (conninfo : String) : IO PgConn := do
  let conn ← connect conninfo
  let st ← status conn
  match st with
  | .ok => return conn
  | _ =>
    let msg ← errorMessage conn
    throw (IO.userError s!"PostgreSQL connection failed: {msg}")

end Database.PostgreSQL.LibPQ
