/-
  Linen.Database.SQLite.Bindings — Low-level SQLite3 FFI bindings

  Direct Lean 4 bindings to the raw `sqlite3_*` C entry points, mirroring how
  `Linen.Database.PostgreSQL.LibPQ` wraps raw `libpq` entry points. Every
  function here returns SQLite's *raw* `UInt32` result code, undecoded — the
  same role Haskell's `CError`-returning `Database.SQLite3.Bindings` plays
  relative to `Database.SQLite3.Bindings.Types.decodeError`. Decoding into
  `Database.SQLite3.Bindings.Types.Error` and building a nicer `Except`-based
  API is `Linen.Database.SQLite.Direct`'s job, one layer up.

  ## Scope

  This module ports the subset of `direct-sqlite`'s raw bindings actually
  needed by `Direct`/`SQLite3` (open/close/errmsg/interrupt/autocommit,
  `exec`, prepare/step/reset/finalize/clear-bindings, parameter/column
  metadata, binding values, reading columns, and the three result-statistics
  counters). Two upstream features are intentionally **out of scope**,
  documented here rather than silently dropped:

  - `sqlite3_trace` (`setTrace`/`trace` upstream) and the row-callback form
    of `sqlite3_exec` (`execWithCallback`/`execPrint` upstream) both require
    SQLite to call back into a Lean closure through a C function pointer.
    No `ffi/*.c` shim in this codebase currently builds that
    Lean-closure-from-C machinery (`postgres.c`'s `PQnotifies` polling and
    `keychain.c`'s synchronous calls never need it), and introducing it is
    out of scope for this port. `exec` below always passes a `NULL` row
    callback to `sqlite3_exec`, which is a documented no-op, not a partial
    implementation of the full signature.
  - `sqlite3_enable_load_extension` (extension loading) is omitted: it is a
    security-sensitive, rarely-used feature with no consumer anywhere in
    this port (`sqlite-simple` itself never calls it).

  ## Haskell source
  - `Database.SQLite3.Bindings` (`direct-sqlite` package)

  ## FFI
  - Implementation in `ffi/sqlite3_shim.c` (symbols `linen_sqlite3_*`),
    linking against the vendored SQLite amalgamation
    (`ffi/vendor/sqlite3/sqlite3.c`) — see the "Native C library" section of
    `docs/imports/sqlite-simple/dependencies.md`.

  Because these are live database operations, most of the test coverage
  lives one layer up (`Linen.Database.SQLite`'s tests exercise a real
  `:memory:` database through every layer at once); this module's own tests
  additionally exercise the raw bindings directly.
-/

import Linen.Database.SQLite.Bindings.Types

namespace Database.SQLite3.Bindings

open Database.SQLite3.Bindings.Types (Database Statement)

-- ────────────────────────────────────────────────────────────────────
-- Connection management
-- ────────────────────────────────────────────────────────────────────

/-- Open a database connection (`SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE`).
    Always returns a `Database` handle, even on failure — SQLite itself sets
    the `sqlite3*` on failure so the caller can still call `errmsg` on it
    (see <http://sqlite.org/c3ref/open.html>), mirroring
    `Linen.Database.PostgreSQL.LibPQ.connect`. -/
@[extern "linen_sqlite3_open"]
opaque openRaw (path : @& String) : IO (UInt32 × Database)

/-- Close a database connection. Returns the raw result code
    (`SQLITE_OK` on success; `SQLITE_BUSY` if unfinalized statements or
    unfinished backups remain and the *non-`_v2`* semantics were requested —
    but since this binds `sqlite3_close_v2`, closing with pending resources
    instead defers the actual close until they're released, and this always
    returns `SQLITE_OK`). -/
@[extern "linen_sqlite3_close"]
opaque closeRaw (db : Database) : IO UInt32

/-- The English-language error message most recently generated by an
    operation on this connection. -/
@[extern "linen_sqlite3_errmsg"]
opaque errmsg (db : @& Database) : IO String

/-- Ask SQLite to interrupt any long-running operation on this connection at
    its next opportunity. -/
@[extern "linen_sqlite3_interrupt"]
opaque interrupt (db : @& Database) : IO Unit

/-- Whether the connection is currently in autocommit mode (`true`) or a
    `BEGIN`-started transaction is still active (`false`). -/
@[extern "linen_sqlite3_get_autocommit"]
opaque getAutocommit (db : @& Database) : IO Bool

-- ────────────────────────────────────────────────────────────────────
-- Simple query execution
-- ────────────────────────────────────────────────────────────────────

/-- Execute zero or more semicolon-separated SQL statements for their side
    effects, with no per-row callback (see the module doc's Scope section).
    Returns the raw result code and, on failure, an error message. -/
@[extern "linen_sqlite3_exec"]
opaque execRaw (db : @& Database) (sql : @& String) : IO (UInt32 × String)

-- ────────────────────────────────────────────────────────────────────
-- Statement management
-- ────────────────────────────────────────────────────────────────────

/-- Compile the first SQL statement in `sql` into a prepared `Statement`.
    If `sql` contains no statements, returns `(SQLITE_OK, none)`. -/
@[extern "linen_sqlite3_prepare"]
opaque prepareRaw (db : @& Database) (sql : @& String) : IO (UInt32 × Option Statement)

/-- Advance a prepared statement to its next result row (or completion). -/
@[extern "linen_sqlite3_step"]
opaque step (stmt : @& Statement) : IO UInt32

/-- Reset a prepared statement so it can be `step`ped again from the start.
    Does *not* clear parameter bindings; use `clearBindings` for that. -/
@[extern "linen_sqlite3_reset"]
opaque reset (stmt : @& Statement) : IO UInt32

/-- Destroy a prepared statement, releasing its native resources. -/
@[extern "linen_sqlite3_finalize"]
opaque finalizeRaw (stmt : Statement) : IO UInt32

/-- Set every bound parameter of a prepared statement back to `NULL`. -/
@[extern "linen_sqlite3_clear_bindings"]
opaque clearBindings (stmt : @& Statement) : IO UInt32

-- ────────────────────────────────────────────────────────────────────
-- Parameter and column information
-- ────────────────────────────────────────────────────────────────────

/-- The index of the largest (rightmost) bound parameter — not necessarily
    the number of parameters, since numbered placeholders (`?5`) can leave
    gaps. -/
@[extern "linen_sqlite3_bind_parameter_count"]
opaque bindParameterCount (stmt : @& Statement) : IO Types.ParamIndex

/-- The name of the `n`-th SQL parameter (e.g. `":v"`), or `none` for an
    unnamed (`?`) placeholder. -/
@[extern "linen_sqlite3_bind_parameter_name"]
opaque bindParameterName (stmt : @& Statement) (idx : Types.ParamIndex) : IO (Option String)

/-- The index of the named parameter, or `0` if no such parameter exists in
    this statement. -/
@[extern "linen_sqlite3_bind_parameter_index"]
opaque bindParameterIndex (stmt : @& Statement) (name : @& String) : IO Types.ParamIndex

/-- The number of columns in the statement's result set. -/
@[extern "linen_sqlite3_column_count"]
opaque columnCount (stmt : @& Statement) : IO Types.ColumnCount

/-- The declared name of a result column, or `none` if `idx` is out of
    range. -/
@[extern "linen_sqlite3_column_name"]
opaque columnName (stmt : @& Statement) (idx : Types.ColumnIndex) : IO (Option String)

-- ────────────────────────────────────────────────────────────────────
-- Binding values to prepared statements
-- ────────────────────────────────────────────────────────────────────

@[extern "linen_sqlite3_bind_int64"]
opaque bindInt64 (stmt : @& Statement) (idx : Types.ParamIndex) (value : Int64) : IO UInt32

@[extern "linen_sqlite3_bind_double"]
opaque bindDouble (stmt : @& Statement) (idx : Types.ParamIndex) (value : Float) : IO UInt32

/-- Bind a UTF-8 text value (copied by SQLite immediately, via
    `SQLITE_TRANSIENT`). -/
@[extern "linen_sqlite3_bind_text"]
opaque bindText (stmt : @& Statement) (idx : Types.ParamIndex) (value : @& String) : IO UInt32

/-- Bind a raw byte-string (`BLOB`) value (copied by SQLite immediately). -/
@[extern "linen_sqlite3_bind_blob"]
opaque bindBlob (stmt : @& Statement) (idx : Types.ParamIndex) (value : @& ByteArray) : IO UInt32

@[extern "linen_sqlite3_bind_null"]
opaque bindNull (stmt : @& Statement) (idx : Types.ParamIndex) : IO UInt32

-- ────────────────────────────────────────────────────────────────────
-- Reading the result row
-- ────────────────────────────────────────────────────────────────────

/-- The raw `SQLITE_*` datatype code SQLite reports for a result column;
    decode with `Types.ColumnType.ofUInt32`. -/
@[extern "linen_sqlite3_column_type"]
opaque columnType (stmt : @& Statement) (idx : Types.ColumnIndex) : IO UInt32

@[extern "linen_sqlite3_column_int64"]
opaque columnInt64 (stmt : @& Statement) (idx : Types.ColumnIndex) : IO Int64

@[extern "linen_sqlite3_column_double"]
opaque columnDouble (stmt : @& Statement) (idx : Types.ColumnIndex) : IO Float

@[extern "linen_sqlite3_column_text"]
opaque columnText (stmt : @& Statement) (idx : Types.ColumnIndex) : IO String

@[extern "linen_sqlite3_column_blob"]
opaque columnBlob (stmt : @& Statement) (idx : Types.ColumnIndex) : IO ByteArray

-- ────────────────────────────────────────────────────────────────────
-- Result statistics
-- ────────────────────────────────────────────────────────────────────

/-- The `rowid` of the most recent successful `INSERT`. -/
@[extern "linen_sqlite3_last_insert_rowid"]
opaque lastInsertRowId (db : @& Database) : IO Int64

/-- Rows changed, inserted, or deleted by the most recent statement. -/
@[extern "linen_sqlite3_changes"]
opaque changes (db : @& Database) : IO Int64

/-- Total rows changed, inserted, or deleted since this connection was
    opened. -/
@[extern "linen_sqlite3_total_changes"]
opaque totalChanges (db : @& Database) : IO Int64

-- ────────────────────────────────────────────────────────────────────
-- User-defined scalar SQL functions (added for module #16,
-- `Linen.Database.SQLite.Simple.Function` — see that module's doc, and
-- `ffi/sqlite3_shim.c`'s "USER-DEFINED SCALAR FUNCTIONS" section, for the
-- Lean-closure-from-C callback machinery this relies on)
-- ────────────────────────────────────────────────────────────────────

/-- Register a UTF-8 scalar SQL function of `nArg` arguments (`-1` for
    "any number of arguments"). `f` is retained (its reference count
    incremented) by the C shim for as long as SQLite keeps the
    registration, and is invoked once per row for every call to the SQL
    function; it is expected to report its result via `funcResultInt64`/
    `funcResultDouble`/`funcResultText`/`funcResultBlob`/`funcResultNull`
    on the `FuncContext` it is given, and any Lean exception it throws is
    caught by the shim and reported as SQL `NULL` (matching upstream's own
    catch-all `-> funcResultNull` fallback). -/
@[extern "linen_sqlite3_create_function"]
opaque createFunctionRaw (db : @& Database) (name : @& String) (nArg : Int32)
    (deterministic : Bool) (f : Types.FuncContext → Types.FuncArgs → UInt32 → IO Unit) : IO UInt32

/-- Remove every scalar function registration for `name` (across every
    argument count this port can create — see `Linen.Database.SQLite.
    Simple.Function.deleteFunction`'s module doc for why a single raw call
    can't do this: SQLite matches a deletion by `(name, nArg, textRep)`
    triple, so a specific `nArg` must be supplied). -/
@[extern "linen_sqlite3_delete_function"]
opaque deleteFunctionRaw (db : @& Database) (name : @& String) (nArg : Int32) : IO UInt32

/-- The raw `SQLITE_*` datatype code of a scalar function's `idx`-th
    argument (0-based); decode with `Types.ColumnType.ofUInt32`. -/
@[extern "linen_sqlite3_func_arg_type"]
opaque funcArgType (args : @& Types.FuncArgs) (idx : UInt32) : IO UInt32

@[extern "linen_sqlite3_func_arg_int64"]
opaque funcArgInt64 (args : @& Types.FuncArgs) (idx : UInt32) : IO Int64

@[extern "linen_sqlite3_func_arg_double"]
opaque funcArgDouble (args : @& Types.FuncArgs) (idx : UInt32) : IO Float

@[extern "linen_sqlite3_func_arg_text"]
opaque funcArgText (args : @& Types.FuncArgs) (idx : UInt32) : IO String

@[extern "linen_sqlite3_func_arg_blob"]
opaque funcArgBlob (args : @& Types.FuncArgs) (idx : UInt32) : IO ByteArray

@[extern "linen_sqlite3_func_result_int64"]
opaque funcResultInt64 (ctx : @& Types.FuncContext) (v : Int64) : IO Unit

@[extern "linen_sqlite3_func_result_double"]
opaque funcResultDouble (ctx : @& Types.FuncContext) (v : Float) : IO Unit

@[extern "linen_sqlite3_func_result_text"]
opaque funcResultText (ctx : @& Types.FuncContext) (v : @& String) : IO Unit

@[extern "linen_sqlite3_func_result_blob"]
opaque funcResultBlob (ctx : @& Types.FuncContext) (v : @& ByteArray) : IO Unit

@[extern "linen_sqlite3_func_result_null"]
opaque funcResultNull (ctx : @& Types.FuncContext) : IO Unit

end Database.SQLite3.Bindings
