/-
  Linen test suite root.

  Mirrors the `Linen/` source tree under `Tests/Linen/`. Each module asserts
  correctness with `#guard`, so building this library runs every check.

      lake build Tests
-/
import Tests.Linen.Control.ApplicativeTest
import Tests.Linen.Control.ArrowTest
import Tests.Linen.Control.ConcurrentTest
import Tests.Linen.Control.ExceptionTest
import Tests.Linen.Control.AutoUpdateTest
import Tests.Linen.Control.CategoryTest
import Tests.Linen.Control.Concurrent.ChanTest
import Tests.Linen.Control.Concurrent.GreenTest
import Tests.Linen.Control.Concurrent.MVarTest
import Tests.Linen.Control.Concurrent.QSemTest
import Tests.Linen.Control.Concurrent.QSemNTest
import Tests.Linen.Control.MonadTest
import Tests.Linen.Control.Monad.ExceptTest
import Tests.Linen.Control.Monad.ReaderTest
import Tests.Linen.Control.Monad.StateTest
import Tests.Linen.Control.Monad.TransTest
import Tests.Linen.Data.Base64Test
import Tests.Linen.Data.BifunctorTest
import Tests.Linen.Data.ByteStringTest
import Tests.Linen.Data.ByteString.Char8Test
import Tests.Linen.Data.ByteString.LazyTest
import Tests.Linen.Data.ByteString.Lazy.Char8Test
import Tests.Linen.Data.ByteString.ShortTest
import Tests.Linen.Data.ByteString.BuilderTest
import Tests.Linen.Data.CaseInsensitiveTest
import Tests.Linen.Data.Conduit.Internal.PipeTest
import Tests.Linen.Data.Configurator.TypesTest
import Tests.Linen.Data.ConfiguratorTest
import Tests.Linen.Data.IntMapTest
import Tests.Linen.Data.MapTest
import Tests.Linen.Data.SetTest
import Tests.Linen.Data.DefaultTest
import Tests.Linen.Web.CookieTest
import Tests.Linen.DataFrame.Internal.TypesTest
import Tests.Linen.DataFrame.Internal.ColumnTest
import Tests.Linen.DataFrame.IO.CSVTest
import Tests.Linen.DataFrame.DisplayTest
import Tests.Linen.DataFrame.Operations.JoinTest
import Tests.Linen.DataFrame.Operations.SortTest
import Tests.Linen.DataFrame.Operations.StatisticsTest
import Tests.Linen.DataFrame.Operations.AggregationTest
import Tests.Linen.DataFrame.Operations.SubsetTest
import Tests.Linen.DataFrame.Operations.TransformTest
import Tests.Linen.Data.BitsTest
import Tests.Linen.Data.BoolTest
import Tests.Linen.Data.FoldableTest
import Tests.Linen.Data.CharTest
import Tests.Linen.Data.ComplexTest
import Tests.Linen.Data.FixedTest
import Tests.Linen.Data.FunctionTest
import Tests.Linen.Data.FunctorTest
import Tests.Linen.Data.IxTest
import Tests.Linen.Data.ListTest
import Tests.Linen.Data.List.NonEmptyTest
import Tests.Linen.Data.NewtypeTest
import Tests.Linen.Data.OrdTest
import Tests.Linen.Data.ProxyTest
import Tests.Linen.Data.RatTest
import Tests.Linen.Data.IPTest
import Tests.Linen.Data.StringTest
import Tests.Linen.Data.TraversableTest
import Tests.Linen.Data.UniqueTest
import Tests.Linen.Data.VoidTest
import Tests.Linen.Data.Json.TypesTest
import Tests.Linen.Data.Json.EncodeTest
import Tests.Linen.Data.Json.DecodeTest
import Tests.Linen.System.Console.AnsiTest
import Tests.Linen.System.ExitTest
import Tests.Linen.System.Log.FastLoggerTest
import Tests.Linen.Database.PostgreSQL.LibPQ.TypesTest
import Tests.Linen.Database.PostgreSQL.LibPQTest
import Tests.Linen.Database.SQL.ConnectionTest
import Tests.Linen.Database.SQL.EncodersTest
import Tests.Linen.Database.SQL.SessionTest
import Tests.Linen.Database.SQL.DecodersTest
import Tests.Linen.Database.SQL.PoolTest
import Tests.Linen.Database.SQL.StatementTest
import Tests.Linen.Crypto.JOSE.FFITest
import Tests.Linen.Crypto.JOSE.TypesTest
import Tests.Linen.Crypto.JOSE.JWKTest
import Tests.Linen.Crypto.JOSE.JWSTest
import Tests.Linen.Crypto.JOSE.JWTTest
import Tests.Linen.Network.HTTP2.Frame.TypesTest
import Tests.Linen.Network.HTTP2.Frame.DecodeTest
import Tests.Linen.Network.HTTP2.Frame.EncodeTest
import Tests.Linen.Network.HTTP2.HPACK.HuffmanTest
import Tests.Linen.Network.HTTP2.HPACK.TableTest
import Tests.Linen.Network.HTTP2.HPACK.DecodeTest
import Tests.Linen.Network.HTTP2.HPACK.EncodeTest
import Tests.Linen.Network.HTTP2.TypesTest
import Tests.Linen.Network.HTTP2.StreamTest
import Tests.Linen.Network.HTTP2.FlowControlTest
import Tests.Linen.Network.HTTP2.ServerTest
import Tests.Linen.Network.HTTP3.ErrorTest
import Tests.Linen.Network.HTTP3.FrameTest
import Tests.Linen.Network.HTTP3.QPACK.TableTest
import Tests.Linen.Network.HTTP3.QPACK.DecodeTest
import Tests.Linen.Network.HTTP3.QPACK.EncodeTest
import Tests.Linen.Network.HTTP.ChunkedTest
import Tests.Linen.Network.HTTP.DateTest
import Tests.Linen.Network.HTTP.Types.HeaderTest
import Tests.Linen.Network.HTTP.Types.MethodTest
import Tests.Linen.Network.HTTP.Types.StatusTest
import Tests.Linen.Network.HTTP.Types.URITest
import Tests.Linen.Network.HTTP.Types.VersionTest
import Tests.Linen.Network.HTTP.Client.TypesTest
import Tests.Linen.Network.HTTP.Client.RequestTest
import Tests.Linen.Network.HTTP.Client.ResponseTest
import Tests.Linen.Network.Socket.TypesTest
import Tests.Linen.Network.Socket.FFITest
import Tests.Linen.Network.SocketTest
import Tests.Linen.Network.Socket.EventDispatcherTest
import Tests.Linen.Network.Socket.BlockingTest
import Tests.Linen.Network.MimeTest
import Tests.Linen.Options.Applicative.TypesTest
import Tests.Linen.Options.Applicative.BuilderTest
import Tests.Linen.Options.Applicative.ExtraTest
import Tests.Linen.PostgREST.ApiRequest.PreferencesTest
import Tests.Linen.PostgREST.Auth.TypesTest
import Tests.Linen.PostgREST.AuthTest
import Tests.Linen.PostgREST.Cache.SieveTest
import Tests.Linen.PostgREST.Config.JSPathTest
import Tests.Linen.PostgREST.Config.PgVersionTest
import Tests.Linen.PostgREST.Config.ProxyTest
import Tests.Linen.PostgREST.CorsTest
import Tests.Linen.PostgREST.DebounceTest
import Tests.Linen.PostgREST.ListenerTest
import Tests.Linen.PostgREST.LoggerTest
import Tests.Linen.PostgREST.MediaTypeTest
import Tests.Linen.PostgREST.NetworkTest
import Tests.Linen.PostgREST.RangeQueryTest
import Tests.Linen.PostgREST.ResponseTest
import Tests.Linen.PostgREST.Response.GucHeaderTest
import Tests.Linen.PostgREST.Response.PerformanceTest
import Tests.Linen.PostgREST.SchemaCache.IdentifiersTest
import Tests.Linen.PostgREST.ApiRequest.TypesTest
import Tests.Linen.PostgREST.ConfigTest
import Tests.Linen.PostgREST.Config.DatabaseTest
import Tests.Linen.PostgREST.Error.TypesTest
import Tests.Linen.PostgREST.ErrorTest
import Tests.Linen.PostgREST.MainTxTest
import Tests.Linen.PostgREST.Plan.TypesTest
import Tests.Linen.PostgREST.Query.SqlFragmentTest
import Tests.Linen.PostgREST.SchemaCache.RelationshipTest
import Tests.Linen.PostgREST.Plan.ReadPlanTest
import Tests.Linen.PostgREST.Plan.MutatePlanTest
import Tests.Linen.PostgREST.SchemaCache.RepresentationsTest
import Tests.Linen.PostgREST.SchemaCache.RoutineTest
import Tests.Linen.PostgREST.Plan.CallPlanTest
import Tests.Linen.PostgREST.SchemaCache.TableTest
import Tests.Linen.PostgREST.SchemaCacheTest
import Tests.Linen.PostgREST.AppStateTest
import Tests.Linen.PostgREST.MetricsTest
import Tests.Linen.PostgREST.AdminTest
import Tests.Linen.PostgREST.ObservationTest
import Tests.Linen.PostgREST.TimeItTest
import Tests.Linen.PostgREST.UnixTest
import Tests.Linen.PostgREST.VersionTest
import Tests.Linen.PostgREST.AppTest
import Tests.Linen.PostgREST.CLITest
import Tests.Linen.PostgREST.Response.OpenAPITest
