/-
  Linen.Network.OAuth2.Internal — OAuth2 client configuration and tokens

  Port of `hoauth2`'s `Network.OAuth2.Internal` (see
  `docs/imports/hoauth2/dependencies.md`): the `OAuth2` client-configuration
  record, the `AccessToken`/`RefreshToken`/`IdToken`/`ExchangeToken`
  newtypes, `ClientAuthenticationMethod`, and the request/URI helpers
  (`addDefaultRequestHeaders`, `appendQueryParams`, `uriToRequest`).

  ## Substitutions (see `dependencies.md` for the full rationale)
  - `URI.ByteString`'s `URIRef Absolute`/`URI` is `linen`'s own
    `Network.URI.URI` (from the already-ported `network-uri`).
  - `uriToRequest :: MonadThrow m => URI -> m Request` drops the bare
    `MonadThrow` constraint (no `catch`/`handle` logic anywhere in
    `hoauth2` relies on it) in favor of a plain `Except String`-returning
    function; callers needing `IO` can `IO.ofExcept` the result, matching
    `Linen.Control.Exception`'s function-level style.
  - `Lens.Micro`'s `over (queryL . queryPairsL)` becomes a direct helper,
    `appendQueryParams`, on `Network.URI.URI` (three call sites across the
    whole package do not warrant porting a general lens abstraction).
  - `Data.Binary.Instances.Aeson` (a disk-serialization convenience layered
    on `ToJSON`/`FromJSON`, out of scope per `dependencies.md`) is dropped;
    this file has no direct use of it besides the import.
  - `Paths_hoauth2.version` (Cabal-autogenerated) is replaced with `linen`'s
    own version string.
-/

import Linen.Network.URI
import Linen.Network.HTTP.Client.Types
import Linen.Data.Json.Types
import Linen.Data.Default

namespace Network.OAuth2.Internal

open Network.HTTP.Types
open Network.HTTP.Client (Request)
open Data.Json (ToJSON FromJSON Value)

-- ── OAuth2 client configuration ──

/-- OAuth2 client configuration: client credentials plus the three
    endpoints/URIs a flow needs.

    $$\text{OAuth2} = \{ \text{clientId}, \text{clientSecret} : \text{String},\;
      \text{authorizeEndpoint}, \text{tokenEndpoint}, \text{redirectUri} :
      \text{URI} \}$$ -/
structure OAuth2 where
  oauth2ClientId : String := ""
  oauth2ClientSecret : String := ""
  oauth2AuthorizeEndpoint : Network.URI.URI := Network.URI.nullURI
  oauth2TokenEndpoint : Network.URI.URI := Network.URI.nullURI
  oauth2RedirectUri : Network.URI.URI := Network.URI.nullURI
deriving Repr, BEq

instance : Data.Default OAuth2 where
  default := {}

-- ── Tokens ──

/-- An OAuth2 access token. -/
structure AccessToken where
  atoken : String
deriving Repr, BEq

instance : ToJSON AccessToken where toJSON t := .string t.atoken
instance : FromJSON AccessToken where
  parseJSON
    | .string s => .ok ⟨s⟩
    | _ => .error "expected a string for AccessToken"

/-- An OAuth2 refresh token. -/
structure RefreshToken where
  rtoken : String
deriving Repr, BEq

instance : ToJSON RefreshToken where toJSON t := .string t.rtoken
instance : FromJSON RefreshToken where
  parseJSON
    | .string s => .ok ⟨s⟩
    | _ => .error "expected a string for RefreshToken"

/-- An OpenID Connect ID token. -/
structure IdToken where
  idtoken : String
deriving Repr, BEq

instance : ToJSON IdToken where toJSON t := .string t.idtoken
instance : FromJSON IdToken where
  parseJSON
    | .string s => .ok ⟨s⟩
    | _ => .error "expected a string for IdToken"

/-- An authorization code (the "exchange token" traded for an access token). -/
structure ExchangeToken where
  extoken : String
deriving Repr, BEq

instance : ToJSON ExchangeToken where toJSON t := .string t.extoken
instance : FromJSON ExchangeToken where
  parseJSON
    | .string s => .ok ⟨s⟩
    | _ => .error "expected a string for ExchangeToken"

-- ── URI JSON instances ──

/-- `hoauth2` pulls a JSON `FromJSON`/`ToJSON` instance for `URI.ByteString`'s
    `URI` from the separate `uri-bytestring-aeson` package; per
    `dependencies.md`, that package's instance is written directly here
    instead (there being no separate package boundary to preserve in this
    port). Renders/parses through the same `Network.URI.uriToString`/
    `Network.URI.parseURI` this port already uses everywhere else a URI
    needs a textual form; shared by `Network.OAuth2.AuthorizationRequest`'s
    `AuthorizationResponseError` and `Network.OAuth2.TokenRequest`'s
    `TokenResponseError`, both of which carry an optional `error_uri`
    field. -/
instance : ToJSON Network.URI.URI where
  toJSON u := .string (Network.URI.uriToString Network.URI.defaultUserInfoMap u)

instance : FromJSON Network.URI.URI where
  parseJSON
    | .string s =>
      match Network.URI.parseURI s with
      | some u => .ok u
      | none => .error s!"invalid absolute URI: {s}"
    | v => .error s!"expected a string URI, got {repr v}"

-- ── Client authentication methods ──

/-- How the client (relying party) authenticates itself. The client MUST NOT
    use more than one authentication method in each request.

    See RFC 6749 §2.3, https://oauth.net/private-key-jwt/, and RFC 7523. -/
inductive ClientAuthenticationMethod where
  /-- `Authorization: Basic ...` header. -/
  | ClientSecretBasic
  /-- Client id/secret in the POST body. -/
  | ClientSecretPost
  /-- A signed JWT assertion. -/
  | ClientAssertionJwt
deriving Repr, BEq

-- ── Utilities for Request and URI ──

/-- POST body content: a list of key/value pairs. -/
abbrev PostBody := List (String × String)

/-- Request query parameters: a list of key/value pairs. -/
abbrev QueryParams := List (String × String)

/-- `linen`'s substitute for `Paths_hoauth2.version` (a Cabal-autogenerated
    package-version constant with no Lean analogue): this library's own
    version string, used the same way upstream uses its package version —
    to build a `User-Agent` value. -/
def linenVersion : String := "0.5.0"

/-- Default headers every OAuth2 HTTP request should carry:
    a `User-Agent` identifying this library, and `Accept: application/json`. -/
def defaultRequestHeaders : RequestHeaders :=
  [ (hUserAgent, s!"linen-{linenVersion}")
  , (hAccept, "application/json") ]

/-- Prepend `defaultRequestHeaders` to a request's existing headers.

    $$\text{addDefaultRequestHeaders} : \text{Request} \to \text{Request}$$ -/
def addDefaultRequestHeaders (req : Request) : Request :=
  { req with headers := defaultRequestHeaders ++ req.headers }

/-- Append extra query parameters to a URI, keeping any that are already
    present (`hoauth2`'s one direct use of `Lens.Micro`'s
    `over (queryL . queryPairsL)`, ported here as a plain helper since a
    general lens abstraction has only three call sites in the whole
    package — see `dependencies.md`).

    $$\text{appendQueryParams} : \text{QueryParams} \to \text{URI} \to \text{URI}$$ -/
def appendQueryParams (params : QueryParams) (uri : Network.URI.URI) : Network.URI.URI :=
  let encodeParam (kv : String × String) : String :=
    Network.URI.escapeURIString Network.URI.isUnescapedInURIComponent kv.1
      ++ "=" ++ Network.URI.escapeURIString Network.URI.isUnescapedInURIComponent kv.2
  if params.isEmpty then
    uri
  else
    let extra := "&".intercalate (params.map encodeParam)
    { uri with
      uriQuery :=
        if uri.uriQuery.isEmpty then "?" ++ extra
        else uri.uriQuery ++ "&" ++ extra }

/-- Turn a URI into an HTTP `Request` (`GET`, no body).

    Substitutes for upstream's `uriToRequest :: MonadThrow m => URI -> m
    Request` (`parseRequest . serializeURIRef'`): a bare `MonadThrow`
    constraint with no `catch`/`handle` logic at its one call site, so this
    is ported as a plain `Except`-returning function instead (see the
    module doc-comment and `dependencies.md`).

    $$\text{uriToRequest} : \text{URI} \to \text{Except String Request}$$ -/
def uriToRequest (uri : Network.URI.URI) : Except String Request :=
  match uri.uriAuthority with
  | none => .error s!"uriToRequest: URI has no authority: {Network.URI.uriToString id uri}"
  | some auth =>
    let isSecure := uri.uriScheme == "https:"
    if !isSecure && uri.uriScheme != "http:" then
      .error s!"uriToRequest: unsupported scheme: {uri.uriScheme}"
    else
      let host := auth.uriRegName
      let port : UInt16 :=
        match (auth.uriPort.drop 1).toNat? with
        | some p => UInt16.ofNat p
        | none => if isSecure then 443 else 80
      let path := if uri.uriPath.isEmpty then "/" else uri.uriPath
      .ok
        { method := .standard .GET
          host := host
          port := port
          path := path
          queryString := uri.uriQuery
          headers := []
          body := none
          isSecure := isSecure }

end Network.OAuth2.Internal
