/-
  Linen.System.Exit.Lens — `_ExitSuccess`, `_ExitFailure`

  Port of Hackage's `lens-5.3.6`'s `System.Exit.Lens` (fetched and read via
  Hackage's rendered source). Upstream's real content:

  ```
  makePrisms ''ExitCode
  ```

  i.e. one `Prism' ExitCode ()` per nullary constructor and one `Prism'
  ExitCode Int` for the payload-carrying constructor, generated by
  Template Haskell against:

  ```
  data ExitCode = ExitSuccess | ExitFailure Int
  ```

  Since `linen`'s `Linen.System.Exit.ExitCode` has the identical two-
  constructor shape (`success` / `failure (UInt32)`), the same two prisms
  are given here by hand (`linen` has no Template Haskell equivalent to
  derive them automatically, matching every other `makePrisms`-derived
  module ported so far, e.g. `Linen.Control.Exception.Lens`'s per-
  constructor `IO.Error` prisms). -/

import Linen.Control.Lens.Prism
import Linen.System.Exit

namespace Control.Lens

open System (ExitCode)

/-- `_ExitSuccess :: Prism' ExitCode ()`: matches/builds `ExitCode.success`. -/
@[inline] def _ExitSuccess : Prism' ExitCode Unit :=
  prism' (fun _ => .success) (fun c => match c with
    | .success => some ()
    | .failure _ => none)

/-- `_ExitFailure :: Prism' ExitCode Int`: matches/builds `ExitCode.failure`,
    carrying its `UInt32` payload (narrowed from upstream's `Int`, matching
    the underlying type `linen`'s own `ExitCode.failure` already carries). -/
@[inline] def _ExitFailure : Prism' ExitCode UInt32 :=
  prism' .failure (fun c => match c with
    | .success => none
    | .failure n => some n)

end Control.Lens
